### PR TITLE
Clip Segmentation Masking

### PR DESCRIPTION
**Pull request by Nerogar**
This is adding automated masking using Clip Segmentation.

Changes:
1. scripts/clip_segmentation.py: Can either be used as a standalone script, or called from other applications.
2. CaptionBuddy now displays masked parts of images, if a mask exists
3. CaptionBuddy has a new function to batch mask an entire folder
4. Configuration UI has a new input field for a fallback mask prompt. When training an inpainting model, and a mask is missing for some of the samples, the mask is automatically generated using this prompt. If no prompt is specified, no mask will be generated.

### CODE REVIEW

**Comment by devilismyfriend** [comment]
I'm getting this error
File "N:\Github\StableTune3\scripts\configuration_gui.py", line 2050, in caption_buddy
    import captionBuddy
  File "N:\Github\StableTune3\scripts\captionBuddy.py", line 21, in <module>
    from scripts.clip_segmentation import ClipSeg
ModuleNotFoundError: No module named 'scripts.clip_segmentation'

perhaps wrap the import for clipseg with a try and if it fails clone the repo, right now I'm not sure where you're telling ST to download the repo

**Comment by devilismyfriend** [comment]
changing the import line to import clip_segmentation lets me pass it but then I run into self.clip_seg = ClipSeg()
NameError: name 'ClipSeg' is not defined

**Comment by Nerogar** [comment]
It should be `from clip_segmentation import ClipSeg`. I assumed a wrong working directory. Since I'm mostly starting directly from PyCharm, I didn't notice the error. Should be fixed now.

**Comment by devilismyfriend** [comment]
Alright, seems to be working and works well! thanks 👯

**Pull request merged**
